import Gender from './Gender';
import Title from './Title';
import Location from './Location';

/**
 * User type with definition constraints:
 *    id: string(autogenerated)
 *    title: string("mr", "ms", "mrs", "miss", "dr", "")
 *    firstName: string(length: 2-50)
 *    lastName: string(length: 2-50)
 *    gender: string("male", "female", "other", "")
 *    email: string(email)
 *    dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
 *    registerDate: string(autogenerated)
 *    phone: string(phone number - any format)
 *    picture: string(url)
 *    location: object(Location)
 */
type User = {
  id: string;
  title: Title;
  firstName: string;
  lastName: string;
  gender: Gender;
  email: string;
  dateOfBirth?: Date;
  registerDate: Date;
  phone: string;
  picture: string;
  location: Location;
};

export default User;
