import Gender from './Gender';

/**
 * UserPreview type with definition constraints:
 *    id: string(autogenerated)
 *    title: string("mr", "ms", "mrs", "miss", "dr", "")
 *    firstName: string(length: 2-50)
 *    lastName: string(length: 2-50)
 *    picture: string(url)
 */
type UserPreview = {
  id: string;
  title: string;
  firstName: string;
  lastName: string;
  picture: string
};

export default UserPreview;
